packages:
  - packages/*

catalog:
  "@commitlint/cli": 19.6.0
  "@commitlint/config-conventional": 19.6.0
  "@commitlint/prompt": 19.6.0
  "@lerna-lite/cli": 4.4.1
  "@lerna-lite/publish": 4.4.1
  "@lerna-lite/run": 4.4.1
  "@lerna-lite/version": 4.4.1
  conventional-changelog-cli: 2.2.2
  conventional-changelog-conventionalcommits: 9.0.0
